#!/usr/bin/env bash
# One-time setup: make the personal pattern store its own git repo, the same
# way dotfiles are usually handled — local history from day one, a remote
# only if and when you decide to back it up.
set -euo pipefail

HOME_DIR="${PATTERNITY_HOME:-$HOME/.patternity}"
STORE="$HOME_DIR/patterns"
mkdir -p "$STORE"

if [ ! -f "$STORE/WALKING_DOC.md" ]; then
  cat > "$STORE/WALKING_DOC.md" <<'EOF'
# Walking doc

Regenerated by the patternity skill every time a pattern is added or its
state changes. Don't hand-edit this list — edit the individual pattern
files instead.
EOF
  echo "created $STORE/WALKING_DOC.md"
fi

if [ ! -d "$HOME_DIR/.git" ]; then
  git -C "$HOME_DIR" init -q
  git -C "$HOME_DIR" add -A
  git -C "$HOME_DIR" commit -q -m "patternity: initialize pattern store"
  echo "initialized git repo at $HOME_DIR"
else
  echo "$HOME_DIR is already a git repo"
fi

cat <<EOF

To back this up (optional, never done automatically):
  gh repo create <you>/patterns --private --source "$HOME_DIR" --remote origin --push
EOF
